# Site settings
title: Walking an Ancient Path
subtitle: "Living Orthodox Christianity in a Modern World"
header-img: img/home-bg.jpg
email: lynnette@letterperfectllc.com
copyright_name: Lynnette P. Horner
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/ancientpath"
url: "http://letterperfectllc.github.io/ancientpath/"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  lynnette@letterperfectllc.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
